---
- hosts: all
  become: true
  tasks:

  - name: install python3&pip3 and Java Open-Jdk for Ubuntu
    apt:
      name:
        - python3-pip
        - openjdk-8-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Use  pip3 as default pip
    shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

  - name: Use python3 as default python
    shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 1



